// Generated by CoffeeScript 1.9.1

/*
 * FE build config
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var butil, cfg, cndDomain, distPath, htmlTplDist, path, srcPath, st_root, viewsDir;

path = require('path');

butil = require('./lib/butil');

st_root = path.join(__dirname);

viewsDir = 'html/';

cfg = butil.getJSONSync('config.json');

srcPath = cfg.srcPathName;

distPath = cfg.distPathName;

htmlTplDist = cfg.htmlTplDist;

cndDomain = cfg.cndDomain;

module.exports = {
  evn: cfg.evn,
  isCombo: cfg.isCombo,
  rootPath: st_root,
  theme: srcPath,
  views: viewsDir,
  htmlTplSrc: path.join("..", srcPath, viewsDir),
  htmlTplDist: htmlTplDist,
  prefix: cfg.jsPrefix,
  hashLength: cfg.hashLength,
  coreJsName: cfg.jsPrefix + cfg.coreJs.name,
  coreJsMods: cfg.coreJs.mods,
  staticRoot: "http://" + cndDomain + "/",
  staticPath: "http://" + cndDomain + "/" + srcPath + "/",
  cndStaticPath: "http://" + cndDomain + "/" + distPath + "/",
  GLOBALVAR: ("var STATIC_PATH='http://" + cndDomain + "/") + (cfg.evn === "dev" ? srcPath : distPath) + "',VARS=window['VARS']={},_VM_=window['_VM_']={};\n",
  dataPath: './data',
  spriteDataPath: './data/sp.map.json',
  spriteHasPath: './data/sp.has.json',
  jsLibPath: '../' + srcPath + '/js/vendor/',
  docOutPath: '../' + srcPath + '/doc/',
  imgSrcPath: '../' + srcPath + '/_img/',
  cssDistPath: '../' + distPath + '/css/',
  jsDistPath: '../' + distPath + '/js/',
  tplDistPath: '../' + distPath + '/js/',
  imgDistPath: '../' + distPath + '/img/',
  spriteDistPath: '../' + distPath + '/img/sp/',
  cssBgDistPath: '../' + distPath + '/img/bg/',
  cssOutPath: '../' + srcPath + '/_css/',
  jsOutPath: '../' + srcPath + '/_js/',
  tplOutPath: '../' + srcPath + '/js/_tpl/',
  lessPath: '../' + srcPath + '/less/',
  jsSrcPath: '../' + srcPath + '/js/',
  tplSrcPath: '../' + srcPath + '/tpl/',
  spriteSrcPath: '../' + srcPath + '/sprite/',
  spriteLessOutPath: '../' + srcPath + '/less/sprite/',
  spriteImgOutPath: '../' + srcPath + '/_img/sp/',
  mapPath: '../' + distPath + '/map/',
  jsMapName: 'jsmap.json',
  cssMapName: 'cssmap.json',
  cssBgMap: 'cssbgmap.json',
  jsLibsMapName: 'jslibs.json',
  jsDistMapName: 'jslibs.json',
  watchFiles: ['../' + srcPath + '/js/**/*.js', '../' + srcPath + '/sprite/**/*.png', '../' + srcPath + '/less/**/*.less', '../' + srcPath + '/tpl/**/*.html', '../' + srcPath + '/' + viewsDir + '**/*.html', '!../' + srcPath + '/**/.DS_Store']
};
