// Generated by CoffeeScript 1.9.3

/*
移除所有模块
 */
var exec, fs, path;

fs = require('fs');

exec = require('child_process').exec;

path = __dirname + '\\node_modules';

console.log(path);

fs.readdir(path, function(error, files) {
  return files.forEach(function(n, i) {
    var _cmd, stat;
    if (n.indexOf('.') > 0 || n.indexOf('.') === -1) {
      stat = fs.lstatSync(path + '\\' + n);
      if (stat.isDirectory()) {
        _cmd = "npm rm " + n;
        console.log(_cmd);
        return exec(_cmd, function(error, stdout, stderr) {
          if (error) {
            return console.log(error);
          } else {
            return console.log(stdout);
          }
        });
      }
    }
  });
});
