// Generated by CoffeeScript 1.9.1

/*
 * v.build config
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var SiteUrl, WapSiteUrl, _env, _envs, _isDebug, args, butil, cfg, cndDomain, distPath, path, ref, ref1, srcPath, st_root, viewsDir;

path = require('path');

butil = require('./butil');

cfg = require('../config.json');

args = require('yargs').argv;

st_root = process.env.INIT_CWD;

viewsDir = 'html/';

_env = (ref = args.e || args.env) != null ? ref : 'local';

_isDebug = (ref1 = args.d || args.debug) != null ? ref1 : false;

_envs = cfg.envs;

srcPath = cfg.srcPathName;

distPath = cfg.distPathName;

SiteUrl = _envs[_env].SiteUrl;

cndDomain = _envs[_env].cndDomain;

WapSiteUrl = _envs[_env].WapSiteUrl;

module.exports = {
  env: _env,
  isDebug: _isDebug,
  isCombo: cfg.isCombo,
  rootPath: st_root,
  srcPath: cfg.srcPathName,
  distPath: cfg.distPathName,
  views: viewsDir,
  htmlTplSrc: path.join("..", srcPath, viewsDir),
  htmlTplDist: cfg.htmlTplDist,
  phpMapPath: cfg.phpMapPath,
  prefix: cfg.jsPrefix,
  hashLength: cfg.hashLength,
  coreJsName: cfg.jsPrefix + cfg.coreJs.name,
  coreJsMods: cfg.coreJs.mods,
  staticRoot: "http://" + cndDomain + "/",
  staticPath: ("http://" + cndDomain + "/") + (_isDebug || _env !== "local" ? distPath + "/" : srcPath + "/"),
  imgPath: ("http://" + cndDomain + "/") + (_isDebug || _env !== "local" ? distPath + "/img/" : srcPath + "/_img/"),
  cssPath: ("http://" + cndDomain + "/") + (_isDebug || _env !== "local" ? distPath + "/css/" : srcPath + "/_css/"),
  jsPath: ("http://" + cndDomain + "/") + (_isDebug || _env !== "local" ? distPath + "/js/" : srcPath + "/_js/"),
  GLOBALVAR: ("var STATIC_PATH='http://" + cndDomain + "/") + (cfg.evn === "local" ? srcPath : distPath) + "',VARS=window['VARS']={},_VM_=window['_VM_']={};",
  dataPath: './data',
  spriteDataPath: './data/sp.map.json',
  jsLibPath: '../' + srcPath + '/js/vendor/',
  docOutPath: '../' + srcPath + '/doc/',
  imgSrcPath: '../' + srcPath + '/_img/',
  cssDistPath: '../' + distPath + '/css/',
  jsDistPath: '../' + distPath + '/js/',
  tplDistPath: '../' + distPath + '/js/',
  imgDistPath: '../' + distPath + '/img/',
  spriteDistPath: '../' + distPath + '/img/sp/',
  cssBgDistPath: '../' + distPath + '/img/bg/',
  cssOutPath: '../' + srcPath + '/_css/',
  jsOutPath: '../' + srcPath + '/_js/',
  tplOutPath: '../' + srcPath + '/js/_tpl/',
  lessPath: '../' + srcPath + '/less/',
  jsSrcPath: '../' + srcPath + '/js/',
  tplSrcPath: '../' + srcPath + '/tpl/',
  spriteSrcPath: '../' + srcPath + '/sprite/',
  spriteLessOutPath: '../' + srcPath + '/less/sprite/',
  spriteImgOutPath: '../' + srcPath + '/_img/sp/',
  mapPath: '../' + distPath + '/map/',
  jsMapName: 'jsmap.json',
  jsDistMapName: 'jslibs.json',
  cssMapName: 'cssmap.json',
  cssBgMap: 'cssbgmap.json',
  watchFiles: ['../' + srcPath + '/js/**/*.js', '../' + srcPath + '/sprite/**/*.png', '../' + srcPath + '/less/**/*.less', '../' + srcPath + '/tpl/**/*.html', '../' + srcPath + '/' + viewsDir + '**/*.html', '!../' + srcPath + '/**/.DS_Store']
};
