// Generated by CoffeeScript 1.9.1

/**
 * 将CSS的debug文件push到生产目录，并将引用到的背景图片自动添加hash后缀
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var _, _buildCss, _buildPaths, _cssDistPath, _cssMapName, _cssPath, _hashLen, _isCombo, _mapPath, _stream, binit, butil, color, config, cssBgMap, e, errrHandler, fs, gulp, gutil, md5, mincss, path, plumber, pushCss, rename;

fs = require('fs');

path = require('path');

_ = require('lodash');

config = require('../config');

gulp = require('gulp');

gutil = require('gulp-util');

mincss = require('gulp-minify-css');

plumber = require('gulp-plumber');

rename = require('gulp-rename');

color = gutil.colors;

_cssPath = config.cssOutPath;

_cssDistPath = config.cssDistPath;

_cssMapName = config.cssMapName;

_mapPath = config.mapPath;

_hashLen = config.hashLength;

_isCombo = config.isCombo;

binit = require('./binit');

butil = require('./butil');

errrHandler = butil.errrHandler;

md5 = butil.md5;

cssBgMap = {};

try {
  cssBgMap = JSON.parse(fs.readFileSync(path.join(_mapPath, config.cssBgMap), 'utf8'));
} catch (_error) {
  e = _error;
}

_stream = function(files, cb, cb2) {
  var _cndPath, _cssOutPath;
  _cssOutPath = path.join(config.rootPath, config.cssOutPath);
  _cndPath = config.cndStaticPath + 'css/';
  return gulp.src([files]).pipe(plumber({
    errorHandler: errrHandler
  })).pipe(mincss({
    keepBreaks: false,
    compatibility: {
      properties: {
        iePrefixHack: true,
        ieSuffixHack: true
      }
    }
  })).on('data', function(source) {
    var _nameObj, _path, _source, cssBgReg;
    _path = source.path.replace(_cssOutPath, '').replace(/\\/g, '/');
    _nameObj = path.parse(_path);
    _nameObj.hash = md5(source.contents);
    cssBgReg = /url\s*\(([^\)]+)\)/g;
    _source = String(source.contents).replace(cssBgReg, function(str, map) {
      var fontPath, key, val;
      if (map.indexOf('fonts/') !== -1) {
        fontPath = (_cndPath + path.join(_nameObj.dir, map)).replace(/\\/g, '/');
        return str.replace(map, fontPath);
      } else {
        key = map.replace('../_img/', '').replace(/(^\'|\")|(\'|\"$)/g, '');
        val = _.has(cssBgMap, key) ? '../img/' + cssBgMap[key].distname : (map.indexOf('data:') > -1 || map.indexOf('about:') > -1 ? map : '../img/' + key + '?=t' + String(new Date().getTime()).substr(0, 8));
        return str.replace(map, val);
      }
    });
    return cb(_nameObj, _source);
  }).on('end', cb2);
};

_buildCss = function(_filePath, source) {
  butil.mkdirsSync(_cssDistPath);
  return fs.writeFileSync(_filePath, source, 'utf8');
};

_buildPaths = binit.paths;


/*
 * css生产文件构建函数
 * @param {string} file 同gulp.src接口所接收的参数，默认是css源文件的所有css文件
 * @param {function} done 回调函数
 */

pushCss = function(file, done) {
  var _done, _file;
  gutil.log(color.yellow("Push Css to dist."));
  if (!file) {
    _done = function() {};
    _file = _cssPath + '**/*.css';
  } else if (typeof file === 'function') {
    _done = file;
    _file = _cssPath + '**/*.css';
  } else {
    _file = file;
    _done = done;
  }
  return _stream(_file, function(obj, source) {
    var _distPath, _distPath2, _filePath, _filePath2, _source;
    _source = source;
    _distPath = obj.dir + '/' + obj.name + '.' + obj.hash.substr(0, _hashLen) + obj.ext;
    _distPath2 = obj.dir + '/' + obj.name + obj.ext;
    _filePath = path.join(_cssDistPath, _distPath);
    _filePath2 = path.join(_cssDistPath, _distPath2);
    _buildCss(_filePath, _source);
    return _buildCss(_filePath2, _source);
  }, function() {
    return _buildPaths('.css', function() {
      gutil.log(color.green('Pushed!'));
      return _done();
    });
  });
};

module.exports = pushCss;
