// Generated by CoffeeScript 1.9.1

/**
 * html to AMD module js function
 * @date 2015-02-14 15:36:39
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var _, _htmlMinify, _replaceImg, common, config, fs, path;

fs = require('fs');

path = require('path');

_ = require('lodash');

config = require('./config');

common = require('./common');

_replaceImg = common.replaceImg;

_htmlMinify = common.htmlMinify;

module.exports = function(folder, cb) {
  var _tplPath, tplData, tpl_soure;
  cb = cb || function() {};
  if (folder.indexOf('.') === 0 || folder === "") {
    return false;
  }
  _tplPath = config.tplSrcPath + folder;
  tplData = {};
  fs.readdirSync(_tplPath).forEach(function(file) {
    var _file_path, _source, file_name, file_source;
    _file_path = path.join(_tplPath, file);
    if (fs.statSync(_file_path).isFile() && file.indexOf('.html') !== -1 && file.indexOf('.') !== 0) {
      file_name = file.replace('.html', '');
      _source = fs.readFileSync(_file_path, 'utf8');
      file_source = _replaceImg(_source);
      file_source = _htmlMinify(file_source);
      if (file.indexOf('_') === 0) {
        return tplData[file_name] = "<script id=\"tpl_" + folder + file_name + "\" type=\"text/html\">" + file_source + "</script>";
      } else {
        return tplData[file_name] = file_source;
      }
    }
  });
  tpl_soure = "define(function(){return " + (JSON.stringify(tplData)) + ";});";
  fs.writeFileSync(path.join(config.tplOutPath, folder + '.js'), tpl_soure, 'utf8');
  return cb();
};
