// Generated by CoffeeScript 1.9.1

/*
 * 服务端html模板构建和压缩模块
 */
var _, _buildHtml, _hashMaps, _htmlMinify, _replaceImg, butil, color, common, config, errrHandler, fs, getJSONSync, gulp, gutil, include, minifyHTML, path, plumber;

fs = require('fs');

path = require('path');

_ = require('lodash');

gulp = require('gulp');

plumber = require('gulp-plumber');

gutil = require('gulp-util');

config = require('./config');

butil = require('./butil');

getJSONSync = butil.getJSONSync;

errrHandler = butil.errrHandler;

color = gutil.colors;

include = require('./include');

common = require('./common');

minifyHTML = require('gulp-minify-html');

_hashMaps = common.hashMaps;

_replaceImg = common.replaceImg;

_htmlMinify = common.htmlMinify;

_buildHtml = function(data) {
  var _name, _outputPath, _path, _source, e;
  try {
    _path = String(data.path).replace(/\\/g, '/');
    if (_path.indexOf("/" + config.views + "_") > -1) {
      return false;
    }
    _name = _path.split("/" + config.srcPath + "/" + config.views)[1];
    _outputPath = path.join(config.htmlTplDist, _name);
    _source = _replaceImg(String(data.contents));
    if (config.env !== 'local') {
      _source = _htmlMinify(_source);
      gutil.log(color.cyan("'" + _name + "'"), "combined.");
    }
    butil.mkdirsSync(path.dirname(_outputPath));
    return fs.writeFileSync(path.join(_outputPath), _source, 'utf8');
  } catch (_error) {
    e = _error;
    return console.log(e);
  }
};

module.exports = function(file, cb) {
  var files, opts;
  if (typeof file === 'function') {
    files = config.htmlTplSrc + "**/*.html";
    cb = file;
  } else {
    files = file || (config.htmlTplSrc + "**/*.html");
    cb = cb || function() {};
  }
  gutil.log(color.yellow("Combine html templates..."));
  opts = {
    prefix: '@@',
    basepath: '@file',
    staticPaths: {
      css: {
        src: config.cssOutPath,
        dist: config.cssDistPath
      },
      js: {
        src: config.jsOutPath,
        dist: config.jsDistPath
      }
    },
    hashmap: _hashMaps
  };
  return gulp.src([files]).pipe(plumber({
    errorHandler: errrHandler
  })).pipe(include(opts)).on("data", function(_data) {
    return _buildHtml(_data);
  }).on("end", function() {
    gutil.log(color.green("Html templates done!"));
    return cb();
  });
};
