// Generated by CoffeeScript 1.9.3

/*
 * js Lib库插件构建模块
 * 公共的Lib库，挂载在 window.Lib 对象下的扩展插件库
 */
var _, _buildLibs, butil, color, config, errrHandler, fs, gutil, md5, objMixin, path;

fs = require('fs');

path = require('path');

_ = require('lodash');

gutil = require('gulp-util');

color = gutil.colors;

butil = require('./butil');

config = require('./config');

errrHandler = butil.errrHandler;

objMixin = butil.objMixin;

md5 = butil.md5;

_buildLibs = function(cb) {
  var _jsLibs, jslibsJson, jsonData;
  jslibsJson = require(config.dataPath + config.jsDistMapName);
  jsonData = {};
  _jsLibs = config.jsLibs;
  fs.readdirSync(_jsLibs).forEach(function(v) {
    var _json, _paths;
    _paths = path.join(_jsLibs, v, 'dist/paths.json');
    if (fs.statSync(_paths).isFile() && v.indexOf('.') !== 0) {
      _json = require(_paths);
      return jsonData = _.assign(jslibsJson, _json);
    }
  });
  jsonData = JSON.stringify(namePaths, null, 2);
  gutil.log(jsonData);
  !fs.existsSync(config.dataPath) && butil.mkdirsSync(config.dataPath);
  fs.writeFileSync(path.join(config.dataPath, config.jsDistMapName), jsonData, 'utf8');
  gutil.log(color.green(config.jsDistMapName + " build success"));
  return _cb();
};
