// Generated by CoffeeScript 1.9.1

/**
 * json to php function
 * @date 2015-02-14 14:10:22
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var config, fs, jsonToPhp, path;

fs = require('fs');

path = require('path');

config = require('../config');

jsonToPhp = function(cb) {
  var _cb, _distPath, _soure, _srcPath, _temp, key, val;
  _cb = cb || function() {};
  _srcPath = config.mapPath;
  _distPath = config.phpMapPath;
  _temp = [];
  fs.readdirSync(_srcPath).forEach(function(file) {
    var _hash, _jsData, _name, _tempArr, file_name, hash, name, php_file_path;
    if (file.indexOf(".json") !== -1) {
      file_name = file.replace(".json", "");
      php_file_path = path.join(_distPath, file_name + ".php");
      _jsData = JSON.parse(fs.readFileSync(path.join(_srcPath, file), 'utf8'));
      _tempArr = [];
      for (name in _jsData) {
        hash = _jsData[name];
        _name = name.split(".")[0];
        _hash = hash.replace("/", "").split(".")[1];
        _tempArr.push('"' + name + '" => "' + _hash + '"');
      }
      _temp[file_name] = _tempArr.join(',');
      return fs.writeFileSync(php_file_path, '<?php' + '\r\n' + 'return array(' + _tempArr + ');' + '\r\n' + '?>', 'utf8');
    }
  });
  _soure = "";
  for (key in _temp) {
    val = _temp[key];
    _soure += "\"" + key + "\" => array(\r\n" + val + "\r\n)" + ",\r\n";
  }
  fs.writeFileSync(path.join(_distPath, 'allhash.php'), '<?php' + "\r\n" + "return array(\r\n" + _soure + ");\r\n" + "?>", "utf8");
  return _cb();
};

module.exports = jsonToPhp;
