// Generated by CoffeeScript 1.9.1

/**
 * json to php function
 * @date 2015-02-14 14:10:22
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var config, fs, jsonToPhp, path;

fs = require('fs');

path = require('path');

config = require('./config');

jsonToPhp = function(cb) {
  var _cb, _distPath, _srcPath, _temp;
  _cb = cb || function() {};
  _srcPath = config.mapPath;
  _distPath = config.phpMapPath;
  _temp = [];
  fs.readdirSync(_srcPath).forEach(function(file) {
    var _hash, _jsonData, _name, _tempArr, file_name, name, php_file_path, val;
    if (file.indexOf(".json") !== -1) {
      file_name = file.replace(".json", "");
      php_file_path = path.join(_distPath, file_name + ".php");
      _jsonData = JSON.parse(fs.readFileSync(path.join(_srcPath, file), 'utf8'));
      _tempArr = [];
      for (name in _jsonData) {
        val = _jsonData[name];
        _name = val.distname;
        _hash = val.hash;
        _tempArr.push("'" + name + "' => array('distname' => '" + _name + "', 'hash' => '" + _hash + "')");
      }
      _temp[file_name] = _tempArr.join();
      return fs.writeFileSync(php_file_path, '<?php' + '\r\n' + 'return array(' + _tempArr + ');' + '\r\n' + '?>', 'utf8');
    }
  });
  return _cb();
};

module.exports = jsonToPhp;
